import { Info } from './info.model';

export const INFOS: Info[] = [
    new Info('Keylor Navas', 30, 'Keeper', 'He is quick, has great reflexes, always positions himself well and is one of the best in one-to-ones; Keylor Navas has everything it takes to be an exceptional keeper.'),
    new Info('Daniel Carvajal Ramos', 25, 'Defender', 'Local full-back Dani Carvajal started his career at the Real Madrid youth academy and is particularly noted for his speed and the composure he displays in his position.'),
    new Info('Marcelo Viera', 29, 'Defender', 'Marcelo came to Europe when he was 18 having already triumphed in Brazil. He is a very fast, attacking full-back who has worked hard since his arrival to take the opportunities that his coaches have given him to secure a place in the first team.'),
    new Info('Toni Kroos', 27, 'Midfielder', 'Real Madrid have, in this central midfielder, a leader who is capable of making the right choice in every situation, with incredible vision to provide assists for teammates, an impressive strike of the ball and terrific dead ball delivery. His versatility means that he can play anywhere in the midfield.'),
    new Info('Cristiano Ronaldo', 32, 'Forward', 'Cristiano Ronaldo is a player who is destined to make history. Thanks to his immense natural talent, the Portuguese forward is a commanding leader for Real Madrid and his national team. He started his career at Andorinha, a small club from his home town where his father worked as the kit man. At just 11 years of age, he caught the attention of one of the greatest clubs in his country, Sporting Clube de Portugal. This was just the beginning of the unstoppable rise to success of a player who is a born winner and shows a level of drive and ambition that is only found among the greatest footballers in history.'),
];
